[
build
]
  command = "npm run build:docs"
  publish = "apps/docs/.next"
  
[
build.environment
]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  TURBO_TEAM = "your-team-name"
  TURBO_TOKEN = "your-token-here"